blog/urls.py
from django.conf.urls import url
from . import views, feed

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name='index'),
    url(r'^(?P<slug>\S+)$', views.BlogDetail.as_view(), name='detail'),
    url(r'^feed/$', feed.LatestPosts(), name='feed'),
]

jobs/urls.py
from django.conf.urls import url
from . import views, feed

urlpatterns = [
    url(r'^$', views.JobIndex.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.JobDetail.as_view(), name='detail'),
    url(r'^feed/$', feed.LatestJobs(), name='feed'),
]

newblog2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^markdown/', include('django_markdown.urls')),
    url(r'^snippets/', include('snippets.urls', namespace='snippets')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^jobs/', include('jobs.urls', namespace='jobs')),
    url(r'^', include('snippets.urls', namespace='snippets')),
]

news/urls.py
from django.conf.urls import url
from . import views, feed

urlpatterns = [
    url(r'^$', views.NewsIndex.as_view(), name='index'),
    url(r'^(?P<slug>\S+)$', views.NewsDetail.as_view(), name='detail'),
    url(r'^feed/$', feed.LatestNews(), name='feed'),
]

snippets/urls.py
from django.conf.urls import url
from . import views, feed

urlpatterns = [
    url(r'^$', views.SnippetIndex.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.SnippetDetail.as_view(), name='detail'),
    url(r'^feed/$', feed.LatestSnippets(), name='feed'),
]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Tag(models.Model):
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.slug

class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)

class Entry(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField(max_length=200, unique=True)
    publish = models.BooleanField(default=True)
    created = models.DateTimeField()
    modified = models.DateTimeField()
    tags = models.ManyToManyField(Tag)

    objects = EntryQuerySet.as_manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug':self.slug})

    class Meta:
        verbose_name = 'Blog Entry'
        verbose_name_plural = 'Blog Entries'
        ordering = ['-created']

jobs/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class JobRequirement(models.Model):
    requirement = models.CharField(max_length=50, unique=True, help_text='Enter the requirement name.')
    number_of_years = models.IntegerField()

    def __str__(self):
        return self.requirement

    class Meta:
        verbose_name = 'Job Requirement'
        verbose_name_plural = 'Job Requirements'
        ordering = ['requirement']


class JobContact(models.Model):
    job_contact_name = models.CharField(max_length=50, help_text='Enter the job contact name.')
    job_contact_email = models.EmailField()
    job_contact_phone = models.CharField(max_length=15)
    job_contact_phone_extension = models.CharField(max_length=20, help_text='Phone number extension')

    def __str__(self):
        return self.job_contact_name

    class Meta:
        verbose_name = 'Job Contact'
        verbose_name_plural = 'Job Contacts'
        ordering = ['job_contact_name']


class JobType(models.Model):
    job_type = models.CharField(max_length=20, unique=True, help_text='Select Job Type')

    def __str__(self):
        return self.job_type

    class Meta:
        verbose_name = 'Job Type'
        verbose_name_plural = 'Job Types'
        ordering = ['-job_type']

class JobQuerySet(models.QuerySet):
    def published(self):
        return self.filter(job_post_published=True)

class Job(models.Model):
    job_title = models.CharField(max_length=50, help_text='Enter the job title.')
    job_description = models.TextField(help_text='Enter the job description.')
    job_company = models.CharField(max_length=50, help_text='Enter the company name.')
    job_post_date = models.DateTimeField()
    job_mod_date = models.DateTimeField()
    job_post_end_date = models.DateTimeField()
    job_post_publish_date = models.DateTimeField()
    job_type = models.ForeignKey(JobType)
    job_require = models.ForeignKey(JobRequirement)
    job_contact = models.ForeignKey(JobContact)
    job_post_published = models.BooleanField(default=True)

    objects = JobQuerySet.as_manager()

    def __str__(self):
        return self.job_title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.get_object().id })

    class Meta:
        verbose_name = 'Job'
        verbose_name_plural = 'Jobs'
        ordering = ['-job_post_date']

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.

class NewsSource(models.Model):
    source = models.CharField(max_length=200, help_text='Source of the News Article')
    source_ref = models.URLField()

    def __str__(self):
        return self.source

    class Meta:
        verbose_name = 'News Source'
        verbose_name_plural = 'News Sources'


class NewsQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)


class NewsStory(models.Model):
    news_title = models.CharField(max_length=200, help_text='News Story Title')
    slug = models.SlugField(max_length=200, unique=True, help_text='News Story URL Path')
    author = models.ForeignKey(User, null=True, blank=True)
    story = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField()
    source = models.ManyToManyField(NewsSource)
    source_link = models.URLField()
    publish = models.BooleanField()

    objects = NewsQuerySet.as_manager()

    def __str__(self):
        return self.news_title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug':self.slug })

    class Meta:
        verbose_name = 'News Story'
        verbose_name_plural = 'News Stories'
        ordering = ['-create_date']

snippets/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.
class SnippetTag(models.Model):
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.slug

    class Meta:
        verbose_name = 'Snippet Tag'
        verbose_name_plural = 'Snippet Tags'
        ordering = ['slug']


class Snippet(models.Model):
    snippet_title = models.CharField(max_length=200, help_text='Limit your snippet titles to 200 characters.')
    snippet_body = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField()
    publish = models.BooleanField()
    snippet_tags = models.ManyToManyField(SnippetTag)
    author = models.ForeignKey(User, null=True, blank=True)

    def __str__(self):
        return self.snippet_title

    def get_absolute_url(self, pk):
        return reverse('detail', (), {'pk': self.pk})

    class Meta:
        verbose_name = 'Python Snippet'
        verbose_name_plural = 'Python Snippets'
        ordering = ['-create_date']

blog/views.py
from django.views import generic
from . import models
# Create your views here.

class BlogIndex(generic.ListView):
    queryset = models.Entry.objects.published()
    template_name = 'index.html'
    paginate_by = 4

class BlogDetail(generic.DetailView):
    model = models.Entry
    template_name = 'post.html'

jobs/views.py
from django.views import generic
from . import models

# Create your views here.

class JobIndex(generic.ListView):
    queryset = models.Job.objects.published()
    template_name = 'job_list.html'
    paginate_by = 20

class JobDetail(generic.DetailView):
    model = models.Job
    template_name = 'job_detail.html'

news/views.py
from django.views import generic
from . import models

# Create your views here.

class NewsIndex(generic.ListView):
    queryset = models.NewsStory.objects.published()
    template = 'news_list.html'
    paginate_by = 10

class NewsDetail(generic.DetailView):
    model = models.NewsStory
    template = 'news_detail.html'

snippets/views.py
from django.views import generic
from . import models

# Create your views here.

class SnippetIndex(generic.ListView):
    queryset = models.Snippet.objects.all()
    template_name = 'snippet_list.html'
    paginate_by = 25

class SnippetDetail(generic.DetailView):
    model = models.Snippet
    template_name = 'snippet_detail.html'

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Craig Derington">
    <link rel="icon" href="{% static "icons/favicon.ico" %}">
    <link href="/feed/" rel="alternate" type="application/rss+xml" title="Django Blog Feed" />
    <title>Django Code Library &raquo; Python, Django & MongoDB! &raquo; craigderington.pythonanywhere.com </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Django Code Library</i></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="/"><i class="fa fa-bitbucket-square"></i> Code</a></li>
              <li><a href="/news/"><i class="fa fa-newspaper-o"></i> News</a></li>
              <li><a href="/jobs/"><i class="fa fa-keyboard-o"></i> Jobs</a></li>
            </ul>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">Django Code Library</h1>
        <p class="lead blog-description">Powered by <a href="https://www.pythonanywhere.com" target="_blank">PythonAnywhere</a> and <a href="https://www.djangoproject.com/" target="_blank">Django 1.8.6</a></p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">
          {% block blog_entries %} {% endblock %}

          {% if is_paginated %}
            <ul class="pager">
              <li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>Prev</a></li>
              <li {% if not page_obj.has_next %}class="disabled"{% endif %}><a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Next</a></li>
            </ul>
    {% endif %}
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4><i class="fa fa-user"></i> About Craig Derington</h4>
            <p>A <b>Veteran web developer</b> with more than <em>20 years experience</em> designing and building web-based database applications. A Passionate and Experienced Pythonista, Craig spends his time espousing the virtues of Django, Object Oriented programming, RESTful web services, <a href="https://www.mercurial-scm.org/" target="_blank">Mercurial</a>, <a href="http://www.bitbucket.org" target="_blank">BitBucket</a> and <a href="http://chimera.labs.oreilly.com/books/1234000000754" target="_blank">Test Driven Development</a>.  Read about my adventures... </p>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

        <div class="blog-footer">
            <p>
                <i class="fa fa-copyright"></i> 2014 - {% now 'Y' %} Craig Derington. <br />  Designed and Built with <i class="fa fa-heart"></i> in Oviedo, FL. <br /> Hosted by PythonAnywhere on <i class="fa fa-linux"></i>.
            </p>
        </div>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load django_markdown %}

{% block blog_entries %}
{% for object in object_list %}
    <div class="post">
        <h2><a href="{% url 'detail' slug=object.slug %}">{{ object.title }}</a></h2>
        <p class="meta">{{ object.created }} <br />
        Tags: {{ object.tags.all|join:', ' }}
        </p>
        {{ object.body|markdown }}
    </div>
{% endfor %}
{% endblock %}

templates/job_detail.html
{% extends 'jobs_base.html' %}
{% load django_markdown %}

{% block job_entries %}
    <div class="post">
        <h2><a href="{% url 'jobs:detail' object.id %}">{{ object.job_title }}</a></h2>
        <p class="small">Company: {{ object.job_company }}</p>
        <p class="meta">Date Added: {{ object.job_post_date }}</p>
        <p>{{ object.job_description|markdown }}</p>
        <p>&nbsp;</p>
        <p class="small">Job Post Expires: {{ object.job_post_end_date}}
    </div>
    <div style="margin-top:15px;margin-bottom:25px;">
      <a href="../" class="btn btn-md btn-primary"><i class="fa fa-arrow-circle-left"></i> Return to List</a>
    </div>
{% endblock %}

templates/jobs/job_detail.html
{% extends 'jobs_base.html' %}
{% load django_markdown %}

{% block job_entries %}
    <div class="post">
        <h2><a href="{% url 'jobs:detail' object.id %}">{{ object.job_title }}</a></h2>
        <p class="small">Company: {{ object.job_company }}</p>
        <p class="meta">Date Added: {{ object.job_post_date }}</p>
        <p>{{ object.job_description|markdown }}</p>
    </div>
    <div style="margin-top:15px;">
      <a href="../" class="btn btn-md btn-primary"><i class="fa fa-arrow-circle-left"></i> Return to List</a>
    </div>
{% endblock %}

templates/jobs/job_list.html
{% extends 'jobs_base.html' %}
{% load django_markdown %}

{% block job_entries %}

{% for object in object_list %}
    <div class="post">
        <h3><a href="{% url 'jobs:detail' object.id %}">{{ object.job_title }}</a></h3>
        <p class="meta">{{ object.job_post_date }}</p>
        <p class="meta">Company: {{object.job_company }}</p>
        <p>{{ object.job_description|markdown}}</p>
        <p>&nbsp;</p>
        <p class="small">Job Post Expires: {{ object.job_post_end_date}}
    </div>
{% endfor %}
{% endblock %}

templates/jobs_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Craig Derington">
    <link rel="icon" href="{% static "icons/favicon.ico" %}">
    <link href="/feed/" rel="alternate" type="application/rss+xml" title="Django Blog Feed" />
    <title>Django and Python Jobs &raquo; Python, Django & MongoDB! &raquo; craigderington.pythonanywhere.com </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Django Code Library</i></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="/"><i class="fa fa-bitbucket-square"></i> Code</a></li>
              <li><a href="/news/"><i class="fa fa-newspaper-o"></i> News</a></li>
              <li class="active"><a href="/jobs/"><i class="fa fa-keyboard-o"></i> Jobs</a></li>
            </ul>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">Django &amp; Python Jobs</h1>
        <p class="lead blog-description">Powered by <a href="https://www.pythonanywhere.com" target="_blank">PythonAnywhere</a> and <a href="https://www.djangoproject.com/" target="_blank">Django 1.8.6</a></p>
      </div>

      <div class="row">

        <div class="col-sm-12 blog-main">
          {% block job_entries %} {% endblock %}

          {% if is_paginated %}
            <ul class="pager">
              <li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>Prev</a></li>
              <li {% if not page_obj.has_next %}class="disabled"{% endif %}><a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Next</a></li>
            </ul>
          {% endif %}
        </div><!-- /.blog-main -->

        <!--
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4><i class="fa fa-user"></i> About Craig Derington</h4>
            <p>A <b>Veteran web developer</b> with more than <em>20 years experience</em> designing and building web-based database applications. A Passionate and Experienced Pythonista, Craig spends his time espousing the virtues of Django, Object Oriented programming, RESTful web services, <a href="https://www.mercurial-scm.org/" target="_blank">Mercurial</a>, <a href="http://www.bitbucket.org" target="_blank">BitBucket</a> and <a href="http://chimera.labs.oreilly.com/books/1234000000754" target="_blank">Test Driven Development</a>.  Read about my adventures... </p>
          </div>
        </div>
        -->

      </div><!-- /.row -->

    </div><!-- /.container -->

        <div class="blog-footer">
            <p>
                <i class="fa fa-copyright"></i> 2014 - {% now 'Y' %} Craig Derington. <br />  Designed and Built with <i class="fa fa-heart"></i> in Oviedo, FL. <br /> Hosted by PythonAnywhere on <i class="fa fa-linux"></i>.
            </p>
        </div>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

  </body>
</html>

templates/news/news_detail.html
{% extends 'news_base.html' %}
{% load django_markdown %}

{% block news_entries %}
    <div class="post">
        <h2>{{ object.news_title }}</h2>
        <p class="meta">Date Added: {{ object.create_date }}</p>
        <p class="small">Author: {{ object.author }}</p>
        <p>{{ object.story }}</p>
        <p>&nbsp;</p>
        <p class="small">Source: {{ object.source_link }}</p>
    </div>
    <div style="margin-top:15px;">
      <a href="../" class="btn btn-md btn-primary"><i class="fa fa-arrow-circle-left"></i> Return to List</a>
    </div>
{% endblock %}

templates/news/news_list.html
{% extends 'news_base.html' %}
{% block news_entries %}

{% for object in object_list %}
    <div class="post">
        <h3><a href="{% url 'news:news_detail' slug=object.slug %}">{{ object.news_title }}</a></h3>
        <p class="meta">{{ object.create_date }}</p>
        <p class="meta">Author: {{object.author }}</p>
        <p>{{ object.story }}</p>
        <p class="small" style="margin-top:15px;">Source: {{ object.source }}</p>
    </div>
{% endfor %}
{% endblock %}

templates/news/newsstory_detail.html
{% extends 'news_base.html' %}
{% load django_markdown %}

{% block news_entries %}
    <div class="post">
        <h2>{{ object.news_title }}</a></h2>
        <p class="meta">Date Added: {{ object.create_date }}</p>
        <p class="small">Author: {{ object.author }}</p>
        <p>{{ object.story|markdown }}</p>
        <p>&nbsp;</p>
        <p class="small">Source: {{ object.source_link }}</p>
    </div>
    <div style="margin-top:15px;">
      <a href="../" class="btn btn-md btn-primary"><i class="fa fa-arrow-circle-left"></i> Return to List</a>
    </div>
{% endblock %}

templates/news/newsstory_list.html
{% extends 'news_base.html' %}
{% load django_markdown %}

{% block news_entries %}

{% for object in object_list %}
    <div class="post">
        <h3><a href="{% url 'news:detail' object.slug %}">{{ object.news_title }}</a></h3>
        <p class="meta">Author: {{object.author }} wrote on {{ object.create_date }}</p>
        <p>{{ object.story|markdown }}</p>
        <p class="small" style="margin-top:15px;">Source: <a href="{{ object.source_link }}" target="_blank"> {{ object.source_link }}</a></p>
    </div>
{% endfor %}
{% endblock %}

templates/news_detail.html
{% extends 'snippet_base.html' %}

{% block news_entries %}
    <div class="post">
        <h2>{{ object.news_title }}</a></h2>
        <p class="meta">Date Added: {{ object.create_date }}</p>
        <p class="small">Author: {{ object.author }}</p>
        <p>{{ object.story }}</p>
        <p>&nbsp;</p>
        <p class="small">Source: {{ object.source }}</p>
    </div>
    <div style="margin-top:15px;">
      <a href="../" class="btn btn-md btn-primary"><i class="fa fa-arrow-circle-left"></i> Return to List</a>
    </div>
{% endblock %}

templates/news_list.html
{% extends 'news_base.html' %}
{% block news_entries %}

{% for object in object_list %}
    <div class="post">
        <h3><a href="{% url 'news:news_detail' slug=object.slug %}">{{ object.news_title }}</a></h3>
        <p class="meta">{{ object.create_date }}</p>
        <p class="meta">Author: {{object.author }}</p>
        <p>{{ object.story }}</p>
        <p class="small" style="margin-top:15px;">Source: {{ object.source }}</p>
    </div>
{% endfor %}
{% endblock %}

templates/post.html
{% extends 'base.html' %}
{% load django_markdown %}

{% block blog_entries %}
    <div class="post">
        <h2><a href="{% url 'detail' slug=object.slug %}">{{ object.title }}</a></h2>
        <p class="meta">{{ object.created }} <br />
        Tags: {{ object.tags.all|join:', ' }}
        </p>
        {{ object.body|markdown }}
    </div>
{% endblock %}

templates/snippet_detail.html
{% extends 'snippet_base.html' %}
{% load django_markdown %}

{% block snippet_entries %}
    <div class="post">
        <h2>{{ object.snippet_title }}</a></h2>
        <p class="meta">Date Added: {{ object.create_date }}</p>
        <p class="small">Author: {{ object.author }}</p>
        <p>{{ object.snippet_body|markdown }}</p>
        <p>&nbsp;</p>
        <p class="small">Tags: {{ object.snippet_tags.all|join:', ' }}</p>
    </div>
    <div style="margin-top:15px;">
      <a href="../" class="btn btn-md btn-primary"><i class="fa fa-arrow-circle-left"></i> Return to List</a>
    </div>
{% endblock %}

templates/snippet_list.html
{% extends 'snippet_base.html' %}
{% block snippet_entries %}

<div style="margin-top:-30px;">
  <form class="form-inline" method="post" action="">
    {% csrf_token %}
    <div class="form-group">
      <input name="search_snippets" size="40" type="text" id="search_snippets" class="form-control" placeholder="Search Code Snippets">
      <button name="search" class="btn btn-sm btn-default"><i class="fa fa-search"></i> Search</button>
    </div>
    <span class="pull-right">
        <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Add Code Snippet</a>
    </span>
  </form>
</div>

<div style="margin-top:20px;">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Added</th>
          <th>Author</th>
          <th>Rating</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <!--<td><a href="../snippets/{{ object.id }}/">{{ object.snippet_title }}</a></td>-->
            <td><a href="{% url 'snippets:detail' object.id %}">{{ object.snippet_title }}</a></td>
            <td>{{ object.create_date }}</td>
            <td>{{ object.author }}</td>
            <td><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <td colspan="4" class="small"><span class="label label-default">{{ object_list.count }} snippets found...</span></td>
        </tr>
      </tfoot>
    </table>
</div>
{% endblock %}

templates/snippets/snippet_detail.html
{% extends 'snippet_base.html' %}
{% load django_markdown %}

{% block snippet_entries %}
    <div class="post">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- DjangoSnippets-1 -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-8276817011304511"
                 data-ad-slot="2922707988"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>

        <h2>{{ object.snippet_title }}</a></h2>
        <p class="meta">Date Added: {{ object.create_date }}</p>
        <p class="small">Author: {{ object.author }}</p>
        <p>{{ object.snippet_body|markdown }}</p>
        <p>&nbsp;</p>
        <p class="small">Tags: {{ object.snippet_tags.all|join:', ' }}</p>
    </div>
    <div style="margin-top:15px;">
      <a href="../" class="btn btn-md btn-primary"><i class="fa fa-arrow-circle-left"></i> Return to List</a>
    </div>
{% endblock %}